apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: "2025-11-28T16:56:18Z"
    labels:
      component: apiserver
      provider: kubernetes
    name: kubernetes
    namespace: default
    resourceVersion: "68"
    uid: fdbbcfee-0d40-445e-a703-18d505a8d922
  spec:
    clusterIP: 10.43.0.1
    clusterIPs:
    - 10.43.0.1
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - name: https
      port: 443
      protocol: TCP
      targetPort: 6443
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"test-service","namespace":"default"},"spec":{"ports":[{"port":8080,"protocol":"TCP","targetPort":8080}],"selector":{"app":"test-app"}}}
    creationTimestamp: "2025-11-28T18:06:19Z"
    name: test-service
    namespace: default
    resourceVersion: "3320"
    uid: 9acada8f-9904-485e-abf1-c24ce84a78c2
  spec:
    clusterIP: 10.43.218.11
    clusterIPs:
    - 10.43.218.11
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      app: test-app
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: "2025-11-28T18:42:15Z"
    finalizers:
    - service.kubernetes.io/load-balancer-cleanup
    labels:
      app.kubernetes.io/component: proxy
      app.kubernetes.io/managed-by: envoy-gateway
      app.kubernetes.io/name: envoy
      gateway.envoyproxy.io/owning-gateway-name: homelab-gateway
      gateway.envoyproxy.io/owning-gateway-namespace: envoy-gateway-system
    name: envoy-envoy-gateway-system-homelab-gateway-00f55f79
    namespace: envoy-gateway-system
    resourceVersion: "2216551"
    uid: c765e14f-4223-4c63-9bc7-896b707b51cc
  spec:
    allocateLoadBalancerNodePorts: true
    clusterIP: 10.43.13.137
    clusterIPs:
    - 10.43.13.137
    externalTrafficPolicy: Local
    healthCheckNodePort: 32525
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - name: http-80
      nodePort: 31046
      port: 80
      protocol: TCP
      targetPort: 10080
    selector:
      app.kubernetes.io/component: proxy
      app.kubernetes.io/managed-by: envoy-gateway
      app.kubernetes.io/name: envoy
      gateway.envoyproxy.io/owning-gateway-name: homelab-gateway
      gateway.envoyproxy.io/owning-gateway-namespace: envoy-gateway-system
    sessionAffinity: None
    type: LoadBalancer
  status:
    loadBalancer:
      ingress:
      - ip: 10.0.0.102
        ipMode: VIP
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"app.kubernetes.io/instance":"eg","app.kubernetes.io/managed-by":"Helm","app.kubernetes.io/name":"gateway-helm","app.kubernetes.io/version":"latest","control-plane":"envoy-gateway","helm.sh/chart":"gateway-helm-v0.0.0-latest"},"name":"envoy-gateway","namespace":"envoy-gateway-system"},"spec":{"ports":[{"name":"grpc","port":18000,"targetPort":18000},{"name":"ratelimit","port":18001,"targetPort":18001},{"name":"wasm","port":18002,"targetPort":18002},{"name":"metrics","port":19001,"targetPort":19001},{"name":"webhook","port":9443,"targetPort":9443}],"selector":{"app.kubernetes.io/instance":"eg","app.kubernetes.io/name":"gateway-helm","control-plane":"envoy-gateway"}}}
      meta.helm.sh/release-name: eg
      meta.helm.sh/release-namespace: envoy-gateway-system
    creationTimestamp: "2025-11-28T17:40:07Z"
    labels:
      app.kubernetes.io/instance: eg
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: gateway-helm
      app.kubernetes.io/version: latest
      control-plane: envoy-gateway
      helm.sh/chart: gateway-helm-v0.0.0-latest
    name: envoy-gateway
    namespace: envoy-gateway-system
    resourceVersion: "4419"
    uid: c29d24de-19dc-4286-92af-a7f96d5cbad7
  spec:
    clusterIP: 10.43.55.29
    clusterIPs:
    - 10.43.55.29
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - name: grpc
      port: 18000
      protocol: TCP
      targetPort: 18000
    - name: ratelimit
      port: 18001
      protocol: TCP
      targetPort: 18001
    - name: wasm
      port: 18002
      protocol: TCP
      targetPort: 18002
    - name: metrics
      port: 19001
      protocol: TCP
      targetPort: 19001
    - name: webhook
      port: 9443
      protocol: TCP
      targetPort: 9443
    selector:
      app.kubernetes.io/instance: eg
      app.kubernetes.io/name: gateway-helm
      control-plane: envoy-gateway
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      objectset.rio.cattle.io/applied: H4sIAAAAAAAA/4ySQYvbMBCF/0p5Z9m142TjFfRQdimUQgmk7aXsQZYnG9W2JKRJSgj+70WJl00b0vZm8958vHmjI5Q33yhE4ywk9iUEOmNbSKwp7I0mCAzEqlWsII9Q1jpWbJyN6dc1P0hzJM6DcblWzD3lxr01iQBxU3c/LYXsed9BoqvihbIvxZtPxrbv3rets/9EWDUQJLQL1Nr4X/bolU4z3a6hLB4i0wABH9xAvKVdTG7vAkPivlxUV1rUQfkE4LAjjAK9aqg/1dHVMVPev8DPidJnsMR0mtb9LjKFLE71Tpg/bdNeDy7Q4+f1X/baqriFRKNpVlez+7ouy+W8UkVV36lmURab2eZuSZvlfDYv9GKZ8k7si4i3ahkFoiedVptyf1xBoizyeZUXeVlAvAoR8vul9CRg/Ac1mP6wcr3Rh/SojH3uac1Kd6lXFzhNHV8indOcy19Up+LZaddD4uvjCqO4dGas/S33l4ff3ANxMPqVne567X8SiNSTZhduHHMcx18BAAD//5X9LCMyAwAA
      objectset.rio.cattle.io/id: ""
      objectset.rio.cattle.io/owner-gvk: k3s.cattle.io/v1, Kind=Addon
      objectset.rio.cattle.io/owner-name: coredns
      objectset.rio.cattle.io/owner-namespace: kube-system
      prometheus.io/port: "9153"
      prometheus.io/scrape: "true"
    creationTimestamp: "2025-11-28T16:56:24Z"
    labels:
      k8s-app: kube-dns
      kubernetes.io/cluster-service: "true"
      kubernetes.io/name: CoreDNS
      objectset.rio.cattle.io/hash: bce283298811743a0386ab510f2f67ef74240c57
    name: kube-dns
    namespace: kube-system
    resourceVersion: "281"
    uid: 427d36a9-08b7-4069-b611-9880df1def45
  spec:
    clusterIP: 10.43.0.10
    clusterIPs:
    - 10.43.0.10
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - name: dns
      port: 53
      protocol: UDP
      targetPort: 53
    - name: dns-tcp
      port: 53
      protocol: TCP
      targetPort: 53
    - name: metrics
      port: 9153
      protocol: TCP
      targetPort: 9153
    selector:
      k8s-app: kube-dns
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      objectset.rio.cattle.io/applied: H4sIAAAAAAAA/4SQQWsbMRCF/0p5Z9nNep04FfRQWnopBUNKL6WHWe04VleWhGa8xZj970UbFxLaJCchvZn3vqczKPvvXMSnCIuxgcHgYw+LOy6jdwyDAyv1pAR7BsWYlNSnKPWaul/sVFiXxaelI9XAS5/e+uoA86yefkcui/txgMXQyiNlbMybLz727z/0fYqvWkQ6MGxFLN7JQriMXObjgf31bcnkqsVw7HghJ1E+YDII1HGYO1ahRFaWuujCUfRRhIWWY016Onbh+vqE6wWePckeFnTdt527uWrc7abhZtXuqF11q83uev2uu2HabK46t1tTJfxvdTy8P1NKMrtayefPdPDhtE3BuxMstoV3XD4dKdwpuQEGORUV2B/nvzl71SwXAXa9bg1ySZpcCrD49nELA6Vyz7qdJy4L008D4cBOU5l/81YWlPO/4NM0/QkAAP//sKxN444CAAA
      objectset.rio.cattle.io/id: ""
      objectset.rio.cattle.io/owner-gvk: k3s.cattle.io/v1, Kind=Addon
      objectset.rio.cattle.io/owner-name: metrics-server-service
      objectset.rio.cattle.io/owner-namespace: kube-system
    creationTimestamp: "2025-11-28T16:56:24Z"
    labels:
      kubernetes.io/cluster-service: "true"
      kubernetes.io/name: Metrics-server
      objectset.rio.cattle.io/hash: a5d3bc601c871e123fa32b27f549b6ea770bcf4a
    name: metrics-server
    namespace: kube-system
    resourceVersion: "326"
    uid: e654b077-1110-4f97-b26a-55cb4aaaf7b1
  spec:
    clusterIP: 10.43.197.64
    clusterIPs:
    - 10.43.197.64
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: PreferDualStack
    ports:
    - name: https
      port: 443
      protocol: TCP
      targetPort: https
    selector:
      k8s-app: metrics-server
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"app":"llama-cpp","component":"llm-server"},"name":"llama-cpp","namespace":"llm"},"spec":{"ports":[{"name":"http","port":8080,"protocol":"TCP","targetPort":8080}],"selector":{"app":"llama-cpp"},"type":"ClusterIP"}}
    creationTimestamp: "2025-12-07T16:34:53Z"
    labels:
      app: llama-cpp
      component: llm-server
    name: llama-cpp
    namespace: llm
    resourceVersion: "698974"
    uid: a53adb5f-d59f-4502-bb50-e2e094556e07
  spec:
    clusterIP: 10.43.153.175
    clusterIPs:
    - 10.43.153.175
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      app: llama-cpp
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"app":"log-analyzer"},"name":"log-analyzer","namespace":"log-analyzer"},"spec":{"ports":[{"name":"http","port":8000,"protocol":"TCP","targetPort":8000}],"selector":{"app":"log-analyzer"},"type":"ClusterIP"}}
    creationTimestamp: "2025-12-27T01:02:48Z"
    labels:
      app: log-analyzer
    name: log-analyzer
    namespace: log-analyzer
    resourceVersion: "2213915"
    uid: 0dea1d44-bd85-4053-a987-00c9fb59fd30
  spec:
    clusterIP: 10.43.88.187
    clusterIPs:
    - 10.43.88.187
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - name: http
      port: 8000
      protocol: TCP
      targetPort: 8000
    selector:
      app: log-analyzer
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      meta.helm.sh/release-name: alloy
      meta.helm.sh/release-namespace: logging
    creationTimestamp: "2025-11-29T01:30:28Z"
    labels:
      app.kubernetes.io/component: networking
      app.kubernetes.io/instance: alloy
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: alloy
      app.kubernetes.io/part-of: alloy
      app.kubernetes.io/version: v1.11.3
      helm.sh/chart: alloy-1.4.0
    name: alloy
    namespace: logging
    resourceVersion: "29056"
    uid: a58513a9-f978-4531-bac8-2c8edb7751e7
  spec:
    clusterIP: 10.43.82.125
    clusterIPs:
    - 10.43.82.125
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - name: http-metrics
      port: 12345
      protocol: TCP
      targetPort: 12345
    selector:
      app.kubernetes.io/instance: alloy
      app.kubernetes.io/name: alloy
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      meta.helm.sh/release-name: grafana
      meta.helm.sh/release-namespace: logging
    creationTimestamp: "2025-11-29T01:39:41Z"
    labels:
      app.kubernetes.io/instance: grafana
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: grafana
      app.kubernetes.io/version: 12.3.0
      helm.sh/chart: grafana-10.2.0
    name: grafana
    namespace: logging
    resourceVersion: "29724"
    uid: 9c0375a8-0a06-4d9a-8c42-a599711265e6
  spec:
    clusterIP: 10.43.2.145
    clusterIPs:
    - 10.43.2.145
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - name: service
      port: 80
      protocol: TCP
      targetPort: grafana
    selector:
      app.kubernetes.io/instance: grafana
      app.kubernetes.io/name: grafana
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      meta.helm.sh/release-name: loki
      meta.helm.sh/release-namespace: logging
    creationTimestamp: "2025-11-29T00:37:17Z"
    labels:
      app.kubernetes.io/instance: loki
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: loki
      app.kubernetes.io/version: 3.3.0
      helm.sh/chart: loki-6.21.0
    name: loki
    namespace: logging
    resourceVersion: "25604"
    uid: 397a5b87-44b2-49c1-a0d5-6d578b9e1612
  spec:
    clusterIP: 10.43.179.45
    clusterIPs:
    - 10.43.179.45
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - name: http-metrics
      port: 3100
      protocol: TCP
      targetPort: http-metrics
    - name: grpc
      port: 9095
      protocol: TCP
      targetPort: grpc
    selector:
      app.kubernetes.io/component: single-binary
      app.kubernetes.io/instance: loki
      app.kubernetes.io/name: loki
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      meta.helm.sh/release-name: loki
      meta.helm.sh/release-namespace: logging
    creationTimestamp: "2025-11-29T00:37:17Z"
    labels:
      app.kubernetes.io/instance: loki
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: loki
      app.kubernetes.io/version: 3.3.0
      helm.sh/chart: loki-6.21.0
      prometheus.io/service-monitor: "false"
      variant: headless
    name: loki-headless
    namespace: logging
    resourceVersion: "25591"
    uid: 4c7df91c-5c57-4a4d-8cb3-4f32c71e243b
  spec:
    clusterIP: None
    clusterIPs:
    - None
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - name: http-metrics
      port: 3100
      protocol: TCP
      targetPort: http-metrics
    selector:
      app.kubernetes.io/instance: loki
      app.kubernetes.io/name: loki
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      meta.helm.sh/release-name: loki
      meta.helm.sh/release-namespace: logging
    creationTimestamp: "2025-11-29T00:37:17Z"
    labels:
      app.kubernetes.io/instance: loki
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: loki
      app.kubernetes.io/version: 3.3.0
      helm.sh/chart: loki-6.21.0
    name: loki-memberlist
    namespace: logging
    resourceVersion: "25595"
    uid: deea91e4-2388-41dc-b983-d9cc1c4537e1
  spec:
    clusterIP: None
    clusterIPs:
    - None
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - name: tcp
      port: 7946
      protocol: TCP
      targetPort: http-memberlist
    selector:
      app.kubernetes.io/instance: loki
      app.kubernetes.io/name: loki
      app.kubernetes.io/part-of: memberlist
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      meta.helm.sh/release-name: tempo
      meta.helm.sh/release-namespace: logging
    creationTimestamp: "2025-12-26T23:58:24Z"
    labels:
      app.kubernetes.io/instance: tempo
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: tempo
      app.kubernetes.io/version: 2.9.0
      helm.sh/chart: tempo-1.24.1
    name: tempo
    namespace: logging
    resourceVersion: "2210074"
    uid: 1c0cd762-1558-4b37-a125-b9970348dada
  spec:
    clusterIP: 10.43.254.37
    clusterIPs:
    - 10.43.254.37
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - name: tempo-jaeger-thrift-compact
      port: 6831
      protocol: UDP
      targetPort: 6831
    - name: tempo-jaeger-thrift-binary
      port: 6832
      protocol: UDP
      targetPort: 6832
    - name: tempo-prom-metrics
      port: 3200
      protocol: TCP
      targetPort: 3200
    - name: tempo-jaeger-thrift-http
      port: 14268
      protocol: TCP
      targetPort: 14268
    - name: grpc-tempo-jaeger
      port: 14250
      protocol: TCP
      targetPort: 14250
    - name: tempo-zipkin
      port: 9411
      protocol: TCP
      targetPort: 9411
    - name: tempo-otlp-legacy
      port: 55680
      protocol: TCP
      targetPort: 55680
    - name: tempo-otlp-http-legacy
      port: 55681
      protocol: TCP
      targetPort: 55681
    - name: grpc-tempo-otlp
      port: 4317
      protocol: TCP
      targetPort: 4317
    - name: tempo-otlp-http
      port: 4318
      protocol: TCP
      targetPort: 4318
    - name: tempo-opencensus
      port: 55678
      protocol: TCP
      targetPort: 55678
    selector:
      app.kubernetes.io/instance: tempo
      app.kubernetes.io/name: tempo
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
kind: List
metadata:
  resourceVersion: ""
